# Set up and overview for gene-level differential expression analysis
https://hbctraining.github.io/Intro-to-DGE/lessons/01b_DGE_setup_and_overview.html

```{r}
## Setup
library(BiocManager)
### Bioconductor and CRAN libraries used
library(DESeq2)
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
library(DEGreport)
library(tximport)
library(ggplot2)
library(ggrepel)
```

```{r}
## List all directories containing data  
samples <- list.files(path = "./data", full.names = T, pattern="quant")

## Obtain a vector of all filenames including the path
files <- file.path(samples, "quant.sf")

## Since all quant files have the same name it is useful to have names for each element
names(files) <- str_replace(samples, "./data/", "") %>% 
                str_replace(".salmon", "")
```

```{r}
# Load the annotation table for GrCh38
tx2gene <- read.delim("intermediate/mouse_annotations.tsv", header = TRUE)
head(tx2gene)
```

```{r}
# import a single quant file to check the columns
salmon_example <- read_tsv(files[1])
head(salmon_example)
tail(salmon_example)
```

```{r}
# Run tximport
txi <- tximport(files, type="salmon", tx2gene=tx2gene[,c("tx_id", "gene_id")], 
                countsFromAbundance="lengthScaledTPM", ignoreTxVersion=TRUE)
```

```{r}
# see what elements are in the txi object
attributes(txi)
```

```{r}
# see the first few rows of the counts matrix
head(txi$counts)
```

```{r}
# Write the counts to an object
data <- txi$counts %>% 
  round() %>% 
  data.frame()
head(data)
```

```{r}
# Save the counts matrix to a TSV file
if (!file.exists("intermediate/mouse_counts_matrix.tsv")) {
  write_tsv(data, "intermediate/mouse_counts_matrix.tsv")
  message("File saved to intermediate/mouse_counts_matrix.tsv")
} else {
  message("File already exists. Skipping write.")
}
```

```{r}
## Create a sampletable/metadata
sampletype <- factor(c(rep("BV2", 4), rep("mg_shaking", 4)))
meta <- data.frame(sampletype, row.names = colnames(txi$counts))
meta
```

```{r}
# Save the metadata to a TSV file
if (!file.exists("intermediate/mouse_sample_metadata.tsv")) {
  write_tsv(meta, "intermediate/mouse_sample_metadata.tsv")
  message("File saved to intermediate/mouse_sample_metadata.tsv")
} else {
  message("File already exists. Skipping write.")
}
```